UnpairedReads={}
DiscordantReads=[]
RefStartPos=[]
RefInd={}
MedianInsertionSize=550
ISSD=150
RDWindowSize=100
MixedRDRs=None
ERD=0
SampleNames=None
ThreadN=8
Pool=None
Processes=[]
Manager=None
SampleReadCount=[]
SequenceDepthRatio=[]
RDWindowSums=None
AllReadCount=None
StatisticalRDWindowSums=None#The middle pp part
StatisticalReadCounts=None
class Parameters:
    ScoreThreshold=0.99
    SampleConfidenceThreshold=0.7
    CN2FilterConfidence=0.7