UnpairedReads={}
DiscordantReads=[]
RefStartPos=[]
RefInd={}
MedianInsertionSize=550
ISSD=150
AdaptiveIS=True#will update the average insertion size dynamically
AdaptiveCount=10000
RDWindowSize=100
MixedRDRs=None
ERD=0
SampleNames=None
ThreadN=16
Pool=None
Processes=[]
Manager=None
SampleReadCount=[]
SequenceDepthRatio=[]
RDWindowSums=None
AllReadCount=None
StatisticalRDWindowSums=None#The middle pp part
StatisticalReadCounts=None
StatLocal=False
EDataName=None
EDataPath="data"
GenomeLength=None
MyGenome=None
RParallel=False
SampleNameIndexes={}
MidDataType="HDF5"
class Parameters:
    ScoreThreshold=0#.99
    SampleConfidenceThreshold=0#.7
    CN2FilterConfidence=0#.7