#!/bin/bash 
# Absolute path to this script, e.g. /home/user/bin/foo.sh
SCRIPT=$(readlink -f "$0")
# Absolute path this script is in, thus /home/user/bin
SCRIPTPATH=$(dirname "$SCRIPT")
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$SCRIPTPATH/hdf5/lib
Ref=$1
shift
for var in "$@"
do
	samtools view -T $Ref -@ 8 $var | $SCRIPTPATH/jcinputraw $Ref $var
done
